### ISSUE TITLE
Kartleggingsenheter skal ha kortkode

### ISSUE THREAD

**Issue by stigat** [Artsdatabanken/nin3-kode-api#92]
Øyvind oppdaterer regneark

**Comment by runningbones** [comment]
m005, m020 og m050 kommer med kortkoder

**Comment by runningbones** [comment]
https://artsdatabankenno-my.sharepoint.com/:x:/g/personal/oyvind_bonesronning_artsdatabanken_no/EegJjI08c0RFiwq8ebKgKuUBIuoBWQq3CYu7NeVDuIDk8A?e=kFdqOs

**Comment by stigat** [comment]
![Image](https://github.com/Artsdatabanken/nin3-kode-api/assets/5111069/4348c5ee-1d00-4854-b7c4-b2070f9907ff)
select (Select count(distinct(Kortkode)) from kartleggingsenhet) as antall_unik, 
           (Select count() from kartleggingsenhet) as antall_totalt
